4.3.1　微分

In [62]:
import numpy as np

悪い実装例

In [63]:
def numerical_diff(f, x):
    h = 1e-50
    return (f(x+h) - f(x) / h)

In [64]:
np.float32(1e-50) #丸め誤差で0.0になる

0.0

In [65]:
def numerical_diff(f, x): #中心差分
    h = 1e-4 #0.0001
    return (f(x+h) - f(x-h)) / (2*h)

4.3.3　偏微分

問１：x0=3、x1=4の時のx0に対する偏微分∂f/∂x0を求めよ

In [66]:
def function_tmp1(x0):
    return x0*x0 + 4.0**2.0

numerical_diff(function_tmp1, 3.0)

6.00000000000378

問2：x0=3、x1=4の時のx1に対する偏微分∂f/∂x1を求めよ

In [67]:
def function_tmp2(x1):
    return 3.0**2.0 + x1*x1

numerical_diff(function_tmp2, 4.0)

7.999999999999119

4.4　勾配

In [68]:
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D

In [69]:
def function_2(x):
    return np.sum(x**2)


In [70]:
def numerical_gradient(f, x):
    h = 1e-4  # 0.0001
    grad = np.zeros_like(x) #xと同じ形状の配列を生成
    
    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x+h)の計算
        x[idx] = tmp_val + h
        fxh1 = f(x)  # f(x+h)

        # f(x-h)の計算
        x[idx] = tmp_val - h 
        fxh2 = f(x)  # f(x-h)

        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val  # 値を元に戻す
        
    return grad

In [71]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [72]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [73]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])

4.4.1　勾配法

In [74]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad

    return x

問：f(x0,x1)=x0^2+x1^2の最小値を勾配法で求めよ。

In [75]:
def function_2(x):
    return x[0]**2 + x[1]**2

init_x =np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

学習率が大きすぎる例：lr=10.0

In [76]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=10.0, step_num=100)

array([-2.58983747e+13, -1.29524862e+12])

学習率が小さすぎる例：lr=1e-10

In [77]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=1e-10, step_num=100)

array([-2.99999994,  3.99999992])

4.4.2　ニューラルネットワークに対する勾配

In [78]:
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [79]:
net = simpleNet()
print(net.W) #重みパラメータ

[[ 0.28217796 -1.26107547  1.02406606]
 [-2.59261893  0.89642484 -0.23420978]]


In [80]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-2.16405026  0.05013707  0.40365084]


In [81]:
np.argmax(p)

2

In [82]:
t = np.array([0, 0, 1]) #正解ラベル
net.loss(x, t)

0.5760107702016808

In [83]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.02587345  0.23684473 -0.26271818]
 [ 0.03881018  0.35526709 -0.39407727]]


In [84]:
f = lambda w:net.loss(x,t)
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.02587345  0.23684473 -0.26271818]
 [ 0.03881018  0.35526709 -0.39407727]]
